.config/dotnet-tools.json
.github/workflows/build.yml
.github/workflows/code-check.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml
.github/workflows/unit-tests.yml
.pre-commit-config.yaml
FireboltDotNetSdk.Tests/FireboltClientTest.cs
FireboltDotNetSdk.Tests/FireboltCommandTest.cs
FireboltDotNetSdk.Tests/FireboltConnectionTest.cs
FireboltDotNetSdk.Tests/IntegrationTests.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/Client/FireboltConnection.cs
FireboltNETSDK/Client/FireboltConnectionStringBuilder.cs
FireboltNETSDK/FireboltClient.cs
FireboltNETSDK/Utils/Types.cs

Added CI actions for
- build
- code style
- unit tests
Also added pre-commit hooks config

ci: CI actions

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/ResponseUtilities.cs
FireboltDotNetSdk.Tests/Unit/FireboltCommandTest.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/FireboltClient.cs
FireboltNETSDK/FireboltDotNetSdk.csproj
FireboltNETSDK/Utils/Types.cs

Ticket: https://packboard.atlassian.net/browse/FIR-18775

feat: fir 18775 add support for new date types

---

FireboltDotNetSdk.Tests/Unit/FireboltCommandTest.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/Utils/JsonHelper.cs
FireboltNETSDK/Utils/Types.cs

Ticket : https://packboard.atlassian.net/browse/FIR-19100

fix: Handle value conversion when the type is Nullable(x) and the value to convert is null

---

FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs

Ticket: https://packboard.atlassian.net/browse/FIR-19080

feat: fir 19080 system engine test improvement

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltCommandTest.cs
FireboltNETSDK/Utils/Types.cs

feat(FIR-16858): Boolean data type

---

.github/workflows/integration-tests.yml
FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Integration/IntegrationTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltConnectionTest.cs
FireboltNETSDK/Client/FireRequest.cs
FireboltNETSDK/Client/FireboltConnection.cs
FireboltNETSDK/FireboltClient.cs
FireboltNETSDK/Utils/Constant.cs

Ticket: https://packboard.atlassian.net/browse/FIR-15835?search_id=62d4119d-b621-458e-9afb-c6e5c1c0f74a

feat(FIR-15835): Add support for service account

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Unit/ArrayUtilTest.cs
FireboltDotNetSdk.Tests/Unit/ColumnTypeTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltCommandTest.cs
FireboltDotNetSdk.Tests/Unit/TypesConverterTest.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/FireboltClient.cs
FireboltNETSDK/Utils/ArrayHelper.cs
FireboltNETSDK/Utils/ColumnType.cs
FireboltNETSDK/Utils/Types.cs

Ticket: https://packboard.atlassian.net/browse/FIR-15409
Add support for new types/array/decimal

feat: Add support for new types, arrays and decimal

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs
FireboltDotNetSdk.Tests/ResponseUtilities.cs
FireboltDotNetSdk.Tests/Unit/FireboltCommandTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltExceptionTest.cs
FireboltDotNetSdk.Tests/Unit/TypesConverterTest.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/Client/FireboltConnection.cs
FireboltNETSDK/Exception/FireboltException.cs
FireboltNETSDK/FireboltClient.cs
FireboltNETSDK/Utils/TokenSecureStorage.cs
FireboltNETSDK/Utils/Types.cs

Improve exception handling and move conversion code to the TypeConverter classter class
Ticket: https://packboard.atlassian.net/browse/FIR-16871

feat(FIR-16871): Improve exception handling and move conversion code to the TypeConverter class

---

.github/workflows/unit-tests.yml
FireboltDotNetSdk.Tests/FireboltDotNetSdk.Tests.csproj

Added CI action to verify unit test coverage

ci: Add coverage action

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Unit/TypesConverterTest.cs
FireboltNETSDK/Utils/Types.cs

FIR-16957: Add support for bytea

feat: FIR-16957: Add support for bytea

---

.github/workflows/integration-tests.yml

Update integration testing workflow to use a new setup action v2, which creates new identity engines and databases

ci: Fir 25092 new identity ci

---

.github/workflows/integration-tests.yml
FireboltDotNetSdk.Tests/Integration/ConnectionTest.cs
FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Integration/IntegrationTest.cs
FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltClientTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltConnectionTest.cs
FireboltNETSDK/Client/FireRequest.cs
FireboltNETSDK/Client/FireResponse.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/Client/FireboltConnection.cs
FireboltNETSDK/Client/FireboltConnectionSettings.cs
FireboltNETSDK/Client/FireboltConnectionStringBuilder.cs
FireboltNETSDK/FireboltClient.cs
FireboltNETSDK/Utils/Constant.cs
README.md

Added support for the new identity, extended tests to cover new functionality

feat: New identity

---

.github/workflows/build.yml
README.md

Updated documentation and examples for how to use .NET SDK

docs: Update README.md for 0.x version

---

.github/workflows/build.yml
README.md

Made minor updates and fixed for a new identity documentation

docs: Minor updates to a new identity documentation

---

FireboltDotNetSdk.Tests/FireboltDotNetSdk.Tests.csproj
FireboltDotNetSdk.Tests/Unit/FireboltClientTest.cs
FireboltNETSDK/Client/FireboltConnection.cs
FireboltNETSDK/FireboltClient.cs

What it does:
Fetches a new token on 401

feat: FIR-16888 fetch token when 401

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltCommandTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltDataReaderTest.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/Client/FireboltDataReader.cs
FireboltNETSDK/Client/FireboltParameter.cs
FireboltNETSDK/Utils/Types.cs

Added tests and fixed implementation of arrays

fix: Fir 27494 arrays

---

README.md

Added a lower limit for 1.* .net sdk version

docs: nuget install lower version limit

---

.github/workflows/integration-tests-v1.yml
.github/workflows/integration-tests-v2.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml
FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs

Removed `environment` parameter from all CI jobs, and set `staging` as a default env

ci: remove environment parameter from ci

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Unit/TypesConverterTest.cs
FireboltNETSDK/Client/FireboltDataReader.cs
FireboltNETSDK/Utils/Types.cs

- Fixed inf tests to eliminate division by zero as it's not supported anymore
- Added NaN validation and tests

test: Fix inf and add NaN tests

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs

- Update error message check for system engine error test
- Increase the query size for a long test

test: Fix system engine error check

---

.github/workflows/release.yml

Removed character trimming when getting the previous version of a package.

ci: fix tag generation logic

---

.github/workflows/release.yml

Fix typo in changelog retrieval

ci: Fix tag generation

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Integration/IntegrationSetUp.cs
FireboltDotNetSdk.Tests/Unit/FireboltConnectionTest.cs
FireboltNETSDK/Utils/Constant.cs

Fixed default env value to be `app` rather than `api`

fix: default env value

---

.github/workflows/integration-tests.yml

Fixed integration tests engine v2 condition to run on workflow dispatch

ci: fix integration tests condition

---

FireboltDotNetSdk.Tests/Unit/FireboltConnectionTest.cs

test: Better catalogs check

---

.github/workflows/integration-tests-v1.yml
.github/workflows/integration-tests-v2.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml
FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs

Removing redundant and obsolete parameters from our integration test workflows. Keeping it in line with other repos.
Workflows are working, but some v1 tests are failing. Will make the fixes separately for those.

ci: Cleanup and standardise our workflows

---

FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs

System engine is no longer supported in v1 so I'm removing tests that are now broken because of it.
I'm also removing purely v2 tests. e.g. ATTACH ENGINE is not a valid command in engines v2.

test: Remove obsolete tests

---

FireboltDotNetSdk.Tests/FireboltDotNetSdk.Tests.csproj
FireboltNETSDK/FireboltDotNetSdk.csproj

- Removed NUnit references from the main project file
- Removed redundant dependencies from both main and test project files

build: Fir 35475 move n unit references to a test project in net sdk

---

.github/workflows/build.yml
.github/workflows/code-check.yml
.github/workflows/integration-tests-v1.yml
.github/workflows/integration-tests-v2.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml
FireboltDotNetSdk.Tests/Integration/ConnectionTest.cs
FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs

Also bumping versions of checkout and setup actions to avoid excessive warnings.

test: Fix integration tests

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/Client/FireboltConnection.cs

Fixed async execution functions to account for the command timeout value, that's set for a command

fix: FIR-36807 command timeout parameter is not working in net

---

FireboltDotNetSdk.Tests/Unit/FireboltConnectionTest.cs
FireboltNETSDK/Client/FireboltConnection.cs

Removed validateConnection call from connection open flow

fix: don't initially validate connection

---

FireboltDotNetSdk.Tests/Integration/ConnectionTest.cs
FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltNETSDK/Client/FireboltCommand.cs

Fixed and removed some integration tests to fix the job

ci: Fix integration tests before release

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs

Fix expected error message in an integration test
https://github.com/firebolt-db/firebolt-net-sdk/actions/runs/11954669705

test:fix expected error message

---

FireboltNETSDK/FireboltDotNetSdk.csproj

Downgrade the version from 1.3.5 to 1.3.4 since 1.3.4 is the actual version.

build:downgrade version to correspond to the released one

---

FireboltDotNetSdk.Tests/FireboltDotNetSdk.Tests.csproj
FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Integration/IntegrationTest.cs
FireboltDotNetSdk.Tests/Unit/ColumnTypeTest.cs
FireboltNETSDK/Client/FireboltDataReader.cs
FireboltNETSDK/FireboltDotNetSdk.csproj
FireboltNETSDK/Utils/Types.cs

Added support for geography type

feat: Fir 38077 ecosystem support for geography type for net

---

FireboltNETSDK/Client/FireboltDataReader.cs

As a client suggestion, we improved the isDBNull method in the cases the value is not null by skipping value converting from the GetValueSafely method.

fix: FIR-45674 Improve isDBNull method

---

FireboltDotNetSdk.Tests/Integration/ExecuteTest.cs
FireboltDotNetSdk.Tests/Integration/IntegrationTest.cs
FireboltDotNetSdk.Tests/Integration/SystemEngineTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltCommandTest.cs
FireboltDotNetSdk.Tests/Unit/FireboltConnectionTest.cs
FireboltNETSDK/Client/FireboltCommand.cs
FireboltNETSDK/Client/FireboltConnection.cs
FireboltNETSDK/Client/FireboltConnectionSettings.cs
FireboltNETSDK/Client/FireboltConnectionStringBuilder.cs
FireboltNETSDK/Client/FireboltParameter.cs
FireboltNETSDK/Client/FireboltParameterCollection.cs

All the sonar fixes for FIR-44272

refactor: FIR-44272 server side prepared statement Sonar changes

---

.gitignore
README.md

extra content in this PR: adding the DotSettings.user file to gitignore

docs: add docs related to streaming and prepared statement features
